language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO=1.6.3
  - DJANGO=1.7.10
  - DJANGO=1.8.4
install:
  - pip install -q Django==$DJANGO
  - pip install -q -r requirements.txt
script:
  - flake8
  - py.test
